// <auto-generated />
namespace TechTest01.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class productdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270645264_productdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
